# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://technology.customink.com
title: EngineerInk
title_head: Engineer
title_tail: Ink
subtitle: A CustomInk Technology Blog
author: CustomInk
simple_search: http://google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#        Authors          #
# ----------------------- #

# {first name}-{last name}:
#   display_name: {your name}
#   github: {github username}
#   gravatar: {md5 hash}
#   twitter: {twitter username}

authors:
  andrea-cardy:
    display_name: Andrea Cardy
    github: andreacardy
    bio: 'Andrea is an Engineer at CustomInk.'
  andrew-willis:
    display_name: Andrew Willis
    github: andrewwillis
    gravatar: ba74d77921b4c3da06f27900c62dca32
    twitter: andrewwillis
    bio: 'Andrew is an Engineer at CustomInk.'
  dan-hensgen:
    display_name: Dan Hensgen
    github: dmeiz
    gravatar: 91e24d724bc6c6a648ed3601a9b12207
    twitter: dmeiz
    bio: 'Dan is an Engineer at CustomInk.'
  jake-vanderdray:
    display_name: Jake Vanderdray
    github: clumpidy
    gravatar: 91add4ff5dc22b24fe8df41bbf3a26e7
    twitter: clumpidy
    bio: 'Jake is an Engineer at CustomInk.'
  jason-gilbertson:
    display_name: Jason Gilbertson
    github: jasgilbe
    gravatar: 2c0ff0227b09c6bfbc210a1b14569b83
    bio: 'Jason is an Engineer at CustomInk.'
  john-hall:
    display_name: John Hall
    github: johnbhall
    gravatar: 64d4bf9eff3f2cd85fab1e9bef1683fa
    twitter: johnbhall
    bio: 'John is an Engineer at CustomInk.'
  jon-morton:
    display_name: Jon Morton
    github: jmorton
    gravatar: 53d4ddc41d7cf45d2601c3afc736fc58
    twitter: jmorton
    bio: 'Jon is an Engineer at CustomInk.'
  josh-born:
    display_name: Josh Born
    github: joshuaborn
    bio: 'Josh is an Engineer at CustomInk.'
  justin-molineaux:
    display_name: Justin Molineaux
    github: hellojustin
    twitter: hello_justin
    bio: 'Justin is an Engineer at CustomInk.'
  karle-durante:
    display_name: Karle Durante
    github: karledurante
    gravatar: 41e75ca920386f6949e2f9cc1714d71f
    twitter: karledurante
    bio: 'Karle is an Engineer at CustomInk.'
  nathan-hessler:
    display_name: Nathan Hessler
    github: nhessler
    gravatar: a311a2926f13168a39e6bd0d8d99aef4
    twitter: spune
    bio: 'Nathan Hessler is a developer at <a href="http://www.customink.com">CustomInk</a>. He has recently learned via crossfit and a paleo diet that fitness and health can be as nerdy an endeavor as anything.'
  nathen-harvey:
    display_name: Nathen Harvey
    github: nathenharvey
    gravatar: 11e71f6ebaccce4cf4ff5ccf6d3c5e44
    twitter: nathenharvey
    bio: 'Nathen Harvey is the manager of Web Operations for <a href="http://www.customink.com">CustomInk</a>. Nathen is the co-organizer of the <a href="http://www.meetup.com/DevOpsDC/">DevOpsDC Meetup</a> and the <a href="http://www.meetup.com/Washington-DC-MongoDB-Users-Group">Washington DC MongoDB Users Group</a>. Nathen contributes to open source projects including the <a href="http://www.opscode.com/chef">Opscode Chef</a> framework and regular contributor to the <a href="http://foodfightshow.org">Food Fight Show podcast</a>.  When not working or hosting meetups, Nathen enjoys going to concerts, drinking craft beer, and over sharing on sites like <a href="http://twitter.com/nathenharvey">twitter</a>, <a href="http://untappd.com/user/nathenharvey">untappd</a>, and <a href="https://foursquare.com/nathenharvey">foursquare</a>.'
  nolan-carroll:
    display_name: Nolan Carroll
    github: nolandc
    gravatar: adbffbf924e6d8fc4c40228950bc90af
    twitter: nolancarroll
    bio: 'Nolan is an Engineer at CustomInk.'
  ramez-mourad:
    display_name: Ramez Mourad
    github: ramezjm
    twitter: ramezjm
    bio: 'Ramez is an Engineer at CustomInk.'
  seth-vargo:
    display_name: Seth Vargo
    github: sethvargo
    gravatar: edba34509bbf91d0072c9c8a8f1886be
    twitter: sethvargo
    bio: 'Seth Vargo is the Web Operators intern for <a href="http://www.customink.com">CustomInk</a>. Seth is currently an undergraduate <a href="http://is.hss.cmu.edu/">Information Systems</a> major at <a href="http://cmu.edu">Carnegie Mellon University</a>. Seth is an avid Ruby developer, <a href="http://github.com/sethvargo">github</a> lover, <a href="http://twitter.com/sethvargo">Twitter</a> fanatic, open-source proponent, <a href="http://dribbble.com">dribbble</a> gawker, and run-on sentence creator. In his spare time, Seth enjoys food, soccer, xbox, and doing incredibly nerdy things with electronics (like <a href="http://www.arduino.cc/">Arduino and <a href="http://www.raspberrypi.org/">Raspberry Pi</a>). Seth really enjoys learning new things, especially when those things are incredibly nerdy or on the "bleeding-edge".'
  stafford-brunk:
    display_name: Stafford Brunk
    github: wingrunr21
    gravatar: ef92744f7f3f9325a9fd645a5ffccc41
    twitter: wingrunr21
    bio: 'Stafford is an Engineer at CustomInk.'
  tien-nguyen:
    display_name: Tien Nguyen
    github: nht007
    gravatar: ac278aab807cdeacae2a3de708ff428c
    twitter: nht007
    bio: 'Tien is a Software Engineer for <a href="http://www.customink.com">CustomInk</a>. Tien is an adherent of Software Craftsmanship and has particular interest in principles and practices that facilitate the growth of object oriented software. Tien considers himself language agnostic and is a fan of Ruby, JavaScript, Java, Clojure, and Smalltalk. In his spare time, Tien enjoys rock climbing, cycling, and playing computer games.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/twitter.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html, custom/asides/category_list.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: customink
github_repo_count: 5
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: CustomInkTech
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: custominktechnologyblog
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-32456448-1

# Facebook Like
facebook_like: false
